name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: testing ssh connection
        uses: appleboy/ssh-action@master
        with: 
          host: soulforger.net
          username: simeon
          key: ${{ secrets.SSH_KEY }}
          port: 25540
          script: |
            cd dsa.soulforger.net/api/
            git pull origin master
            ${{ secrets.GIT_UNAME }}
            ${{ secrets.GIT_KEY }}
            sudo docker stop API
            ${{ secrets.SUDO_PW }}
            sudo docker rm API
            sudo docker rmi soulforger-api 
            sudo docker build -t soulforger-api .
            sudo docker run --name API --link mongoDB:mongo -p 8000:8000 -d soulforger-api
            sudo docker ps